dict_of_short_languages_eng = {'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'azerbaijani': 'az', 'basque': 'eu', 'belarusian': 'be',
											  'bengali': 'bn', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca',
											  'cebuano': 'ceb', 'chichewa': 'ny', 'corsican': 'co', 'croatian': 'hr',
											  'czech': 'cs', 'danish': 'da', 'dutch': 'nl',
											  'esperanto': 'eo', 'estonian': 'et', 'filipino': 'tl', 'finnish': 'fi',
											  'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka',
											  'german': 'de', 'greek': 'el', 'gujarati': 'gu', 'haitian creole': 'ht',
											  'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'he', 'hindi': 'hi',
											  'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig',
											  'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja',
											  'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km',
											  'korean': 'ko', 'kurdish (kurmanji)': 'ku', 'kyrgyz': 'ky', 'lao': 'lo',
											  'latin': 'la', 'latvian': 'lv', 'lithuanian': 'lt', 'luxembourgish': 'lb',
											  'macedonian': 'mk', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml',
											  'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'mongolian': 'mn',
											  'myanmar (burmese)': 'my', 'nepali': 'ne', 'norwegian': 'no',
											  'odia': 'or', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl',
											  'portuguese': 'pt', 'punjabi': 'pa', 'romanian': 'ro',
											  'russian': 'ru', 'samoan': 'sm', 'scots gaelic': 'gd',
											  'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn',
											  'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk',
											  'slovenian': 'sl', 'somali': 'so', 'spanish': 'es',
											  'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv',
											  'tajik': 'tg', 'tamil': 'ta', 'telugu': 'te', 'thai': 'th',
											  'turkish': 'tr', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug',
											  'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh',
											  'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}

dict_of_short_languages_ru = {'африкаанс': 'af', 'албанский': 'sq', 'амхарский': 'am', 'арабский': 'ar',
							  'азербайджанский': 'az', 'баскский': 'eu', 'белорусский': 'be',
							  'бенгальский': 'bn', 'боснийский': 'bs', 'болгарский': 'bg', 'каталонский': 'ca',
							  'кебуано': 'ceb', 'чичева': 'ny', 'корсиканский': 'co', 'хорватский': 'hr',
							  'чешский': 'cs', 'датский': 'da', 'голландский': 'nl',
							  'эсперанто': 'eo', 'эстонский': 'et', 'филиппинский': 'tl', 'финский': 'fi',
							  'французский': 'fr', 'фризский': 'fy', 'галисийский': 'gl', 'грузинский': 'ka',
							  'немецкий': 'de', 'греческий': 'el', 'гуджарати': 'gu', 'гаитянский креольский': 'ht',
							  'хауса': 'ha', 'гавайский': 'haw', 'иврит': 'he', 'хинди': 'hi', 'хмонг': 'hmn',
							  'венгерский': 'hu', 'исландский': 'is', 'игбо': 'ig', 'индонезийский': 'id',
							  'ирландский': 'ga', 'итальянский': 'it', 'японский': 'ja', 'яванский': 'jw',
							  'каннада': 'kn', 'казахский': 'kk', 'кхмерский': 'km', 'корейский': 'ko',
							  'курдский (курманджи)': 'ku', 'кыргызский': 'ky', 'лаосский': 'lo', 'латинский': 'la',
							  'латышский': 'lv', 'литовский': 'lt', 'люксембургский': 'lb', 'македонский': 'mk',
							  'малагасийский': 'mg', 'малайский': 'ms', 'малаялам': 'ml', 'мальтийский': 'mt',
							  'маори': 'mi', 'маратхи': 'mr', 'монгольский': 'mn', 'мьянма (бирманский)': 'my',
							  'непальский ': 'ne', 'норвежский': 'no', 'одия': 'or', 'пушту': 'ps', 'персидский': 'fa',
							  'польский': 'pl', 'португальский': 'pt', 'пенджаби': 'pa', 'румынский': 'ro',
							  'русский': 'ru', 'самоанский': 'sm', 'шотландский гэльский': 'gd', 'сербский': 'sr',
							  'сесото': 'st', 'шона': 'sn', 'синдхи': 'sd', 'сингальский': 'si', 'словацкий': 'sk',
							  'словенский': 'sl', 'сомалийский': 'so', 'испанский': 'es', 'суданский': 'su',
							  'суахили': 'sw', 'шведский': 'sv', 'таджикский': 'tg', 'тамильский': 'ta', 'телугу': 'te',
							  'тайский': 'th', 'турецкий': 'tr', 'украинский': 'uk', 'урду': 'ur', 'уйгурский': 'ug',
							  'узбекский': 'uz', 'вьетнамский': 'vi', 'валлийский': 'cy', 'коса': 'xh', 'идиш': 'yi',
							  'йоруба': 'yo', 'зулу': 'zu'}
